In [1]:
import pandas as pd
df_all = pd.read_csv("SGJobData.csv")

len(df_all)

1048585

In [2]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1048585 non-null  int64
 16  salary_minimum                      1048585 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1048585 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 169.0+ MB

In [3]:
df_it = pd.read_csv("jobs_clean.csv")
len(df_it)

140866

In [4]:
df_it.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140866 entries, 0 to 140865
Data columns (total 54 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   categories                          140866 non-null  object
 1   employmentTypes                     140866 non-null  object
 2   metadata_expiryDate                 140866 non-null  object
 3   metadata_isPostedOnBehalf           140866 non-null  bool
 4   metadata_jobPostId                  140866 non-null  object
 5   metadata_newPostingDate             140866 non-null  object
 6   metadata_originalPostingDate        140866 non-null  object
 7   metadata_repostCount                140866 non-null  int64
 8   metadata_totalNumberJobApplication  140866 non-null  int64
 9   metadata_totalNumberOfView          140866 non-null  int64
 10  minimumYearsExperience              140866 non-null  int64
 11  numberOfVacancies                   140866 non-null  int64
 12  positionLevels                      140866 non-null  object
 13  postedCompany_name                  140866 non-null  object
 14  salary_maximum                      140866 non-null  int64
 15  salary_minimum                      140866 non-null  int64
 16  salary_type                         140866 non-null  object
 17  status_id                           140866 non-null  int64
 18  status_jobStatus                    140866 non-null  object
 19  title                               140866 non-null  object
 20  average_salary                      140866 non-null  float64
 21  salary_minimum_raw                  140866 non-null  int64
 22  salary_maximum_raw                  140866 non-null  int64
 23  average_salary_raw                  140866 non-null  float64
 24  title_raw                           140866 non-null  object
 25  position_level_raw                  140866 non-null  object
 26  title_clean                         140866 non-null  object
 27  position_level                      140866 non-null  object
 28  posting_month                       140866 non-null  object
 29  category_list                       140866 non-null  object
 30  category_count                      140866 non-null  int64
 31  it_job_category                     140866 non-null  object
 32  salary_valid                        140866 non-null  bool
 33  salary_midpoint                     140866 non-null  float64
 34  salary_band_width                   140866 non-null  int64
 35  salary_group_count                  140866 non-null  int64
 36  category_position_midpoint          140866 non-null  float64
 37  salary_q1                           140866 non-null  float64
 38  salary_q3                           140866 non-null  float64
 39  salary_iqr                          140866 non-null  float64
 40  salary_lower_bound                  140866 non-null  float64
 41  salary_upper_bound                  140866 non-null  float64
 42  salary_classification               140866 non-null  object
 43  salary_outlier_flag                 140866 non-null  bool
 44  salary_analysis_ready               140866 non-null  bool
 45  salary_review_reason                6363 non-null    object
 46  salary_band_ratio                   140866 non-null  float64
 47  salary_minimum_below_floor          140866 non-null  bool
 48  salary_maximum_above_ceiling        140866 non-null  bool
 49  salary_band_too_wide                140866 non-null  bool
 50  salary_band_ratio_too_high          140866 non-null  bool
 51  salary_threshold_review_flag        140866 non-null  bool
 52  experience_review_flag              140866 non-null  bool
 53  from_may_2023_flag                  140866 non-null  bool
dtypes: bool(11), float64(10), int64(13), object(20)
memory usage: 47.7+ MB

In [5]:
df_all.isnull().sum()

categories                               3988
employmentTypes                          3988
metadata_expiryDate                      3988
metadata_isPostedOnBehalf                   0
metadata_jobPostId                       3988
metadata_newPostingDate                  3988
metadata_originalPostingDate             3988
metadata_repostCount                        0
metadata_totalNumberJobApplication          0
metadata_totalNumberOfView                  0
minimumYearsExperience                      0
numberOfVacancies                           0
occupationId                          1048585
positionLevels                           3988
postedCompany_name                       3988
salary_maximum                              0
salary_minimum                              0
salary_type                              3988
status_id                                   0
status_jobStatus                         3988
title                                    3988
average_salary                              0
dtype: int64

In [6]:
import json
#create a empty list
all_categories = []

for raw in df_all["categories"].dropna():  #go through the categories column one value at a time (after dropping the blank ones), and each time, call the current value raw."
    all_categories.extend(json.loads(raw))

# 2. Build a DataFrame from that list, then keep only unique id/category pairs
category_lookup = pd.DataFrame(all_categories).drop_duplicates().sort_values("id").reset_index(drop=True)

category_lookup

    id                           category
0    1   Accounting / Auditing / Taxation
1    2                Admin / Secretarial
2    3                Advertising / Media
3    4     Architecture / Interior Design
4    5                Banking and Finance
5    6          Building and Construction
6    7                         Consulting
7    8                   Customer Service
8    9                             Design
9   10             Education and Training
10  11                        Engineering
11  12                      Entertainment
12  13               Environment / Health
13  14                Events / Promotions
14  15                                F&B
15  16                 General Management
16  17                       General Work
17  18        Healthcare / Pharmaceutical
18  19                        Hospitality
19  20                    Human Resources
20  21             Information Technology
21  22                          Insurance
22  23                              Legal
23  24           Logistics / Supply Chain
24  25                      Manufacturing
25  26       Marketing / Public Relations
26  27         Medical / Therapy Services
27  28             Personal Care / Beauty
28  29              Professional Services
29  30             Public / Civil Service
30  31         Purchasing / Merchandising
31  32  Real Estate / Property Management
32  33             Repair and Maintenance
33  34                    Risk Management
34  35                     Sales / Retail
35  36        Sciences / Laboratory / R&D
36  37         Security and Investigation
37  38                    Social Services
38  39                 Telecommunications
39  40                   Travel / Tourism
40  41                             Others
41  42                    Wholesale Trade
42  43              Precision Engineering

In [7]:

#Drop occupationId since it is not in use

df_all=df_all.drop(columns =["occupationId"])
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1048585 non-null  int64
 15  salary_minimum                      1048585 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1048585 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(1), int64(8), object(11)
memory usage: 161.0+ MB

In [9]:
#locating the null rows and drop them
null_rows = df_all[df_all["title"].isnull()]

df_all=df_all.dropna(subset=["title"])
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1044597 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), float64(1), int64(8), object(11)
memory usage: 168.4+ MB

In [10]:
df_all["metadata_newPostingDate"].head()

0    2023-04-08
1    2023-04-08
2    2023-04-08
3    2023-04-08
4    2023-04-08
Name: metadata_newPostingDate, dtype: object

In [11]:
df_all["metadata_newPostingDate"] = pd.to_datetime(df_all["metadata_newPostingDate"], format="%Y-%m-%d")
df_all["metadata_originalPostingDate"] = pd.to_datetime(df_all["metadata_originalPostingDate"], format="%Y-%m-%d")
df_all["metadata_expiryDate"] = pd.to_datetime(df_all["metadata_expiryDate"], format="%Y-%m-%d")

In [12]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1044597 entries, 0 to 1048584
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  datetime64[ns]
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  datetime64[ns]
 6   metadata_originalPostingDate        1044597 non-null  datetime64[ns]
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), datetime64[ns](3), float64(1), int64(8), object(8)
memory usage: 168.4+ MB

In [ ]:
before_count = len(df_it)

df_it_filtered = df_it[
    df_it["salary_analysis_ready"]
    .astype(str)
    .str.strip()
    .str.upper()
    .eq("TRUE")
].copy()

after_count = len(df_it_filtered)
reduction = before_count - after_count

print(f"Original records: {before_count}")
print(f"Filtered records: {after_count}")
print(f"Records removed: {reduction}")

Original records: 140866
Filtered records: 134503
Records removed: 6363

In [14]:
#To determine the sum of each employmnet type for all industry
summary = df_all.groupby("employmentTypes")["metadata_jobPostId"].count().sort_values(ascending=False)

summary = summary.reset_index()
summary.columns = ["employmentTypes" , "count"]
summary["percentage"] = (summary["count"]/summary["count"].sum()*100).round(1)
summary

         employmentTypes   count  percentage
0              Permanent  458139        43.9
1              Full Time  393352        37.7
2               Contract  139182        13.3
3              Part Time   25431         2.4
4              Temporary   18241         1.7
5  Internship/Attachment    6959         0.7
6              Freelance    2139         0.2
7             Flexi-work    1154         0.1

In [39]:
%pip install plotly
import plotly.express as px

total_postings = summary["count"].sum()

# group the small categories into "Other"
summary["group"] = summary["employmentTypes"].where(summary["percentage"] >= 3, "Other")
chart_data = summary.groupby("group")[["count"]].sum().reset_index()
chart_data["percentage"] = (chart_data["count"] / chart_data["count"].sum() * 100).round(1)
chart_data = chart_data.sort_values("count", ascending=True)

fig = px.bar(
    chart_data,
    x="count", y="group",
    orientation="h",
    text=chart_data["percentage"].astype(str) + "%",
    labels={"count": "Number of postings", "group": "Employment type"},
    title=f"Employment Type Mix — All Industries<br><sup>Total postings: {total_postings:,}</sup>"
)
fig.update_traces(
    marker_color="#4C6EF5",
    textposition="outside",
    cliponaxis=False
)

fig.update_layout(
    xaxis=dict(
        title=dict(
            text="Number of postings",
            standoff=60
        ),
        range=[0, chart_data["count"].max() * 1.15]
    ),
    yaxis_title=None,
    plot_bgcolor="white",
    margin=dict(b=140, r=80)
)


fig.add_annotation(
    text="Other includes: Part Time, Temporary, Internship/Attachment, Freelance, Flexi-work",
    xref="paper", yref="paper",
    x=0, y=-0.2,
    showarrow=False,
    font=dict(size=11, color="gray"),
    align="left"
)

fig.show()

Requirement already satisfied: plotly in /home/siewyin/miniconda3/envs/pds/lib/python3.10/site-packages (7.0.0)
Requirement already satisfied: narwhals>=1.15.1 in /home/siewyin/miniconda3/envs/pds/lib/python3.10/site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in /home/siewyin/miniconda3/envs/pds/lib/python3.10/site-packages (from plotly) (26.3)
Note: you may need to restart the kernel to use updated packages.

In [42]:
summary_it = df_it_filtered["employmentTypes"].value_counts().reset_index()
summary_it.columns = ["employmentTypes", "count"]
summary_it["percentage"] = (summary_it["count"] / summary_it["count"].sum() * 100).round(1)

total_it_postings = summary_it["count"].sum()

summary_it["group"] = summary_it["employmentTypes"].where(summary_it["percentage"] >= 3, "Other")
chart_data_it = summary_it.groupby("group")[["count"]].sum().reset_index()
chart_data_it["percentage"] = (chart_data_it["count"] / chart_data_it["count"].sum() * 100).round(1)
chart_data_it = chart_data_it.sort_values("count", ascending=True)

fig_it = px.bar(
    chart_data_it,
    x="count", y="group",
    orientation="h",
    text=chart_data_it["percentage"].astype(str) + "%",
    labels={"count": "Number of postings", "group": "Employment type"},
    title=f"Employment Type Mix — IT Postings<br><sup>Total postings: {total_it_postings:,}</sup>"
)
fig_it.update_traces(
    marker_color="#12877F",
    textposition="outside",
    cliponaxis=False
)

fig_it.update_layout(
    xaxis=dict(
        title=dict(
            text="Number of postings",
            standoff=60
        ),
        range=[0, chart_data_it["count"].max() * 1.15]
    ),
    yaxis_title=None,
    plot_bgcolor="white",
    paper_bgcolor="white",
    margin=dict(b=140, r=80)
)


fig_it.add_annotation(
    text="Other includes:<br>"
         "Internship/Attachment, Temporary, Part Time, "
         "Freelance, Flexi-work",
    xref="paper",
    yref="paper",
    x=0,
    y=-0.34,
    showarrow=False,
    font=dict(size=11, color="gray"),
    align="left"
)

fig_it.show()

In [43]:
def summarize(data):
    s = data["employmentTypes"].value_counts().reset_index()
    s.columns = ["employmentTypes", "count"]
    s["percentage"] = (s["count"] / s["count"].sum() * 100).round(1)
    s["group"] = s["employmentTypes"].where(s["percentage"] >= 3, "Other")
    g = s.groupby("group")[["count"]].sum().reset_index()
    g["percentage"] = (g["count"] / g["count"].sum() * 100).round(1)
    return g


all_summary = summarize(df_all).assign(dataset="All Industries")
it_summary = summarize(df_it_filtered).assign(dataset="IT")

combined = pd.concat([all_summary, it_summary])

# fix the bar order so it reads Permanent -> Full Time -> Contract -> Other
order = ["Permanent", "Full Time", "Contract", "Other"]
combined["group"] = pd.Categorical(combined["group"], categories=order, ordered=True)
combined = combined.sort_values("group")

fig = px.bar(
    combined,
    x="percentage",
    y="group",
    color="dataset",
    barmode="group",
    orientation="h",
    text=combined["percentage"].astype(str) + "%",
    labels={
        "percentage": "% of postings",
        "group": "Employment type",
        "dataset": ""
    },
    color_discrete_map={
        "All Industries": "#4C6EF5",  # blue
        "IT": "#12877F"                # green
    },
    title=f"Employment Type Mix: All Industries "
          f"(n={len(df_all):,}) vs IT "
          f"(n={len(df_it_filtered):,})"
)

fig.update_traces(
    textposition="outside",
    cliponaxis=False
)

fig.update_layout(
    xaxis_title=None,
    yaxis_title=None,
    plot_bgcolor="white",
    margin=dict(b=90)
)
fig.add_annotation(
    text="Note: figures are % share within each dataset.<br>Other includes: Part Time, Temporary, Internship/Attachment, Freelance, Flexi-work",
    xref="paper", yref="paper",
    x=0, y=-0.2,
    showarrow=False,
    font=dict(size=11, color="gray"),
    align="left"
)
fig.show()